CREATE TABLE "lawyers" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"institute_name" text NOT NULL,
	"practice_start_year" integer,
	"lawyer_type" text NOT NULL,
	"phone_number" text,
	"email" text,
	"profile_image_url" text,
	"cover_image_url" text,
	"description" text,
	"rating" double precision DEFAULT 0,
	"address" text,
	"city" text,
	"district" text,
	"post_code" text,
	"website" text,
	"business_hours" text,
	"sponsored" boolean DEFAULT false,
	"sponsored_until" date,
	"interested_area" text,
	"institution_id" text,
	"latitude" double precision,
	"longitude" double precision,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
